sudo: required
services:
  - docker

before_install:
  - docker build -t danielespejelps/dock_kube_react -f Dockerfile.dev .

script:
  - docker run -e CI=true danielespejelps/dock_kube_react npm run test 
